export const SKILL_NAME = "skillName"
export const EVENT_TYPE = "eventType"
export const FROM_INDEX = "fromIndex"
export const EQUIP = "equip"
export const UNEQUIP = "unequip"
export const MOVE = "move"
export const DONE = "done"
